version: "3.9"
services:
  ticket-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ticket
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=ticket-svc
      - MYSQL_PASSWORD=ticket-pass
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
