server:
  port: 8080

spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/ticket?serverTimezone=UTC&characterEncoding=UTF-8
    username: ticket-svc
    password: ticket-pass
